import { readFileSync, writeFileSync } from 'fs';
const auth = JSON.parse(readFileSync(process.env.TEMP + '/auth.json', 'utf8'));
const list = await (await fetch('http://127.0.0.1:9222/json/list')).json();
let target = list.find(t => t.type === 'page') || (await (await fetch('http://127.0.0.1:9222/json/new?http://localhost:3000')).json());
const ws = new WebSocket(target.webSocketDebuggerUrl);
let id = 0; const pending = new Map();
ws.addEventListener('message', (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m.result); pending.delete(m.id); } });
const send = (mm, p = {}) => new Promise(r => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({ id: i, method: mm, params: p })); });
const ev = async (x, aw = false) => (await send('Runtime.evaluate', { expression: x, returnByValue: true, awaitPromise: aw, userGesture: true })).result?.value;
const wait = ms => new Promise(r => setTimeout(r, ms));
const shot = async (n) => { const r = await send('Page.captureScreenshot', { format: 'png' }); if (r?.data) writeFileSync(process.env.TEMP + '/' + n, Buffer.from(r.data, 'base64')); };
await new Promise(r => ws.addEventListener('open', r));
await send('Runtime.enable'); await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride', { width: 1500, height: 950, deviceScaleFactor: 1, mobile: false });
await send('Page.navigate', { url: 'http://localhost:3000/login' }); await wait(2500);
const seed = { state: { user: auth.user, accessToken: auth.access_token, refreshToken: auth.refresh_token, activeRole: auth.user?.active_role ?? null }, version: 0 };
await ev(`localStorage.setItem('efms-auth', ${JSON.stringify(JSON.stringify(seed))}); 'ok'`);
await send('Page.navigate', { url: 'http://localhost:3000/dashboard' }); await wait(9000);
await ev(`[...document.querySelectorAll('button,a')].find(b => /my files/i.test(b.textContent) && b.textContent.length<20)?.click()`);
await wait(2500);
const rows = await ev(`JSON.stringify([...document.querySelectorAll('tbody tr')].map(r => { const t=[...r.querySelectorAll('td')].map(c=>c.innerText.replace(/\s+/g,' ').trim()); return {subject:t[1], status:t[5]}; }))`);
console.log('My Files rows:', rows);
await shot('myfiles-status-rule.png');
ws.close();
